name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter analyze
      - run: flutter test

  build_androidApk:
    name: Build Flutter App (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --build-name=1.0.0 --build-number=${{ github.run_number }}
      - name: Rename APK
        run: |
          APP_NAME=$(grep 'name:' pubspec.yaml | sed 's/.*: //')
          VERSION_NAME=$(grep 'version:' pubspec.yaml | sed 's/.*: //; s/+.*//')
          BUILD_NUMBER=${{ github.run_number }}
          
          # Capitalize the first letter of APP_NAME
          APP_NAME_CAPITALIZED="$(tr '[:lower:]' '[:upper:]' <<< "${APP_NAME:0:1}")${APP_NAME:1}"
          
          APK_PATH="build/app/outputs/apk/release/app-release.apk"
          NEW_APK_NAME="${APP_NAME_CAPITALIZED} ${VERSION_NAME}+${BUILD_NUMBER}.apk"
          mv "$APK_PATH" "$NEW_APK_NAME"
          echo "Renamed APK to $NEW_APK_NAME"
          
          # Give variables to github environment
          echo "new_apk_name=$NEW_APK_NAME" >> $GITHUB_ENV
          echo "version_name=$VERSION_NAME" >> $GITHUB_ENV
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/${{ env.new_apk_name }}"
          tag: v${{ env.version_name }}+${{ env.build_number }}
          token: ${{ secrets.TOKEN}}