name: Test and Build

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter analyze
      - run: flutter test --dart-define=IS_TEST=true

  build_androidApk:
    name: Build Flutter App (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # --------- THIS SECTION CAN BE REUSED IN OTHER BUILD WORKFLOWS
      - name: Set environment variables
        run: |
          # Get variables
          APP_NAME=$(grep 'name:' pubspec.yaml | sed 's/.*: //')
          VERSION_NAME=$(grep 'version:' pubspec.yaml | sed 's/.*: //; s/+.*//')
  
          # Capitalize the first letter of APP_NAME
          APP_NAME_CAPITALIZED="$(tr '[:lower:]' '[:upper:]' <<< "${APP_NAME:0:1}")${APP_NAME:1}"
          # Full app name
          FULL_APP_NAME="${APP_NAME_CAPITALIZED}_${VERSION_NAME}"
  
          # Give variables to github environment
          echo "full_app_name=$FULL_APP_NAME" >> $GITHUB_ENV
          echo "version_name=$VERSION_NAME" >> $GITHUB_ENV
  
          # Print variables for debugging
          echo "Full app name: $FULL_APP_NAME"
          echo "Version and build number: $VERSION_NAME"
        # --------- THIS SECTION CAN BE REUSED IN OTHER BUILD WORKFLOWS
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --build-name=${{ env.version_name }} --build-number=${{ github.run_number }} --no-tree-shake-icons
      - name: Rename APK
        run: |
          APK_PATH="build/app/outputs/apk/release/app-release.apk"
          NEW_APK_NAME="${{ env.full_app_name }}.apk"
          mv "$APK_PATH" "$NEW_APK_NAME"
          echo "Renamed APK to $NEW_APK_NAME"
          
          # Give variables to github environment
          echo "new_apk_name=$NEW_APK_NAME" >> $GITHUB_ENV