name: Test only # DONT RENAME THIS OR FILE WILL RESET github.run_number

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # FLUTTER VERSION
          channel: 'stable'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter analyze
      - run: flutter test --dart-define=IS_TEST=true --dart-define=SYNC_TEST_TOKEN=${{ secrets.SYNC_TEST_TOKEN}}
      - run: flutter test test/resources/database/mirror_with_sql_test.dart --dart-define=IS_TEST=false